/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author toshiba
 */
public class SeleccionJugador extends javax.swing.JFrame {

    /**
     * Creates new form RegistroJugador
     */
     ArrayList<Object> jugador=new ArrayList<>();
    int cont=0;
    int victorias=0;
    
    
    ClsControlador controller =new ClsControlador();

    DefaultComboBoxModel listaJugadoresModel = 
            new DefaultComboBoxModel(jugador.toArray());
    
    
    public SeleccionJugador() {
        initComponents();
        
        jugador=controller.extraerObjetos("jugadores.dat");
     
        llenarCombo();
        llenarTabla();
     
     
     if(jugador.size() > 0){
            ClsJugador ultimo = (ClsJugador) jugador.get(jugador.size()-1);
            cont=ultimo.getId();
        }
     //para los botononbes de eliminar y editar esten desabilidatos
        //el lapiz actualiza o edita la lista
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        
    }

    public void llenarCombo(){
       if(jugador.size() > 0){
            cmbJugadores.setEnabled(true);
            
            jugador = controller.extraerObjetos("jugadores.dat");
            cmbJugadores.setModel(new javax.swing.DefaultComboBoxModel(jugador.toArray()));
            cmbJugador1.setModel(new javax.swing.DefaultComboBoxModel(jugador.toArray()));
            cmbJugador2.setModel(new javax.swing.DefaultComboBoxModel(jugador.toArray()));
        }else{
            cmbJugadores.setEnabled(false);
            
        }         
    }
    
    
    
    public void llenarTabla(){
        
        String nombre=txtNombre.getText();
        String apellido=txtApellido.getText();
        String usuario=txtUsuario.getText();
        String cedula=txtCedula.getText();

       if(jugador.size() > 0){         
            ClsJugador est=new ClsJugador(cont,nombre,apellido,cedula,usuario,victorias);
            DefaultTableModel model = (DefaultTableModel) tblRegistros.getModel();
            for(int i = 0; i < jugador.size(); i ++){
                est = (ClsJugador) jugador.get(i);
                Object jugadorG [] = {est.getId(),est.getNombre(),est.getApellido(),est.getCedula(),est.getUsuario()};
                model.insertRow(i, jugadorG);
            }
        }     
       
    }
    
     public void limpiar(){
         
        txtNombre.setText(null);
        txtApellido.setText(null);
        txtCedula.setText(null);
        txtUsuario.setText(null);
        
        btnGuardar.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistroJugador = new javax.swing.JFrame();
        cmbJugadores = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistros = new javax.swing.JTable();
        btnSeleccionPersonaje = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblTituloPersonajes = new javax.swing.JLabel();
        cmbJugador1 = new javax.swing.JComboBox<>();
        cmbJugador2 = new javax.swing.JComboBox<>();
        btnRegistrarJugador = new javax.swing.JButton();
        cmbPersonajes = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnEmpezar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnSelectJugador1 = new javax.swing.JButton();
        bntSelectJugador2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        cmbJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJugadoresActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido");

        jLabel6.setText("Cedula");

        jLabel7.setText("Usuario");

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        tblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id:", "Nombre:", "Apellido:", "Cedula:", "Usuario:", "Victorias:"
            }
        ));
        jScrollPane1.setViewportView(tblRegistros);

        btnSeleccionPersonaje.setText("Ir a la Selección de Personaje");
        btnSeleccionPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionPersonajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegistroJugadorLayout = new javax.swing.GroupLayout(RegistroJugador.getContentPane());
        RegistroJugador.getContentPane().setLayout(RegistroJugadorLayout);
        RegistroJugadorLayout.setHorizontalGroup(
            RegistroJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroJugadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RegistroJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroJugadorLayout.createSequentialGroup()
                        .addGroup(RegistroJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(33, 33, 33)
                        .addGroup(RegistroJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroJugadorLayout.createSequentialGroup()
                        .addComponent(cmbJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addGroup(RegistroJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(RegistroJugadorLayout.createSequentialGroup()
                .addGroup(RegistroJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroJugadorLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistroJugadorLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(btnSeleccionPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        RegistroJugadorLayout.setVerticalGroup(
            RegistroJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroJugadorLayout.createSequentialGroup()
                .addGroup(RegistroJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroJugadorLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(cmbJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(RegistroJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(RegistroJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(RegistroJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroJugadorLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(RegistroJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeleccionPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        lblTitulo.setText("battle pro");

        lblTituloPersonajes.setText("PERSONAJES");

        cmbJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJugador1ActionPerformed(evt);
            }
        });

        btnRegistrarJugador.setText("REGISTRAR JUGADOR");
        btnRegistrarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarJugadorActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        btnEmpezar.setText("Empezar");

        jLabel3.setText("jLabel3");

        btnSelectJugador1.setText("Seleccionar Jugador 1 ");
        btnSelectJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectJugador1ActionPerformed(evt);
            }
        });

        bntSelectJugador2.setText("Seleccionar Jugador 2");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelectJugador1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(cmbJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTitulo))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(bntSelectJugador2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(cmbJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnRegistrarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(btnEmpezar)))
                        .addGap(110, 110, 110))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(lblTituloPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lblTituloPersonajes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(bntSelectJugador2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEmpezar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrarJugador))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSelectJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(121, 121, 121))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarJugadorActionPerformed
        // TODO add your handling code here:
        RegistroJugador.setVisible(true);//Sea visible la ventana de registro
        RegistroJugador.setSize(700,700);//Dimension de la ventana              
    }//GEN-LAST:event_btnRegistrarJugadorActionPerformed

    private void btnSelectJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectJugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectJugador1ActionPerformed

    private void cmbJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJugador1ActionPerformed
        // TODO add your handling code here:   
    }//GEN-LAST:event_cmbJugador1ActionPerformed

    private void cmbJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJugadoresActionPerformed
        // TODO add your handling code here:
        ClsJugador jugadorSeleccionado = (ClsJugador)cmbJugadores.getSelectedItem();

        txtNombre.setText(jugadorSeleccionado.getNombre());
        txtApellido.setText(jugadorSeleccionado.getApellido());
        txtUsuario.setText(jugadorSeleccionado.getUsuario());
        txtCedula.setText(jugadorSeleccionado.getCedula());
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnGuardar.setEnabled(false);

    }//GEN-LAST:event_cmbJugadoresActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String nombre=txtNombre.getText();
        String apellido=txtApellido.getText();
        String usuario=txtUsuario.getText();
        String cedula=txtCedula.getText();
        cont++;

        ClsJugador jugadorP=new ClsJugador(cont, nombre, apellido,cedula, usuario,victorias);
        if( !nombre.equals("") && !apellido.equals("") && !usuario.equals("")&&!cedula.equals("") ){

            jugador.add(jugadorP);
            controller.escribirObjeto("jugadores.dat", jugador);
            jugador=controller.extraerObjetos("jugadores.dat");

            limpiar();
            llenarCombo();

            Object jugadoresG [] = {jugadorP.getId(),jugadorP.getNombre(),jugadorP.getApellido(),jugadorP.getCedula(),jugadorP.getUsuario()};
            DefaultTableModel model = (DefaultTableModel) tblRegistros.getModel();
            model.addRow(jugadoresG);

        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Llene todos los campos");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        ClsJugador jugadorSelect = (ClsJugador)cmbJugadores.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) tblRegistros.getModel();
        //System.out.println(cmbestudiantes.getSelectedIndex());
        //elimina el estudiante de la tabla cn remove row y select index x q elimina el indece d la tabla
        model.removeRow(cmbJugadores.getSelectedIndex());
        jugador.remove(jugadorSelect);
        controller.escribirObjeto("jugadores.dat", jugador);
        llenarCombo();
        limpiar();
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        ClsJugador jugadorSeleccionado = (ClsJugador)cmbJugadores.getSelectedItem();

        jugadorSeleccionado.setNombre(txtNombre.getText());
        jugadorSeleccionado.setCedula(txtCedula.getText());
        jugadorSeleccionado.setApellido(txtApellido.getText());
        jugadorSeleccionado.setUsuario(txtUsuario.getText());

        int id=jugadorSeleccionado.getId();
        String nombre=jugadorSeleccionado.getNombre();
        String apellido=jugadorSeleccionado.getApellido();
        String cedula=jugadorSeleccionado.getCedula();
        String usuario=jugadorSeleccionado.getUsuario();

        Object jugadoresG [] = {id,nombre,apellido,cedula,usuario};
        DefaultTableModel model = (DefaultTableModel) tblRegistros.getModel();
        model.removeRow(cmbJugadores.getSelectedIndex());
        jugador.remove(cmbJugadores.getSelectedIndex());
        model.insertRow(cmbJugadores.getSelectedIndex(), jugadoresG);
        jugador.add(cmbJugadores.getSelectedIndex(), jugadorSeleccionado);
        controller.escribirObjeto("jugadores.dat", jugador);
        llenarCombo();
        limpiar();
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSeleccionPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionPersonajeActionPerformed
        // TODO add your handling code here:
        RegistroJugador.setVisible(false);//Cierra la ventana de registro
    }//GEN-LAST:event_btnSeleccionPersonajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame RegistroJugador;
    private javax.swing.JButton bntSelectJugador2;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrarJugador;
    private javax.swing.JButton btnSeleccionPersonaje;
    private javax.swing.JButton btnSelectJugador1;
    public static javax.swing.JComboBox<String> cmbJugador1;
    public static javax.swing.JComboBox<String> cmbJugador2;
    private javax.swing.JComboBox<String> cmbJugadores;
    private javax.swing.JComboBox<String> cmbPersonajes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloPersonajes;
    private javax.swing.JTable tblRegistros;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
